// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDembYfDpkLOWOP9jbNY5KncXKOQDlGIT0',
    appId: '1:461060498166:web:cc4501386d31ce4e79c2d7',
    messagingSenderId: '461060498166',
    projectId: 'rideshare-007bond',
    authDomain: 'rideshare-007bond.firebaseapp.com',
    storageBucket: 'rideshare-007bond.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUU6uiIrWMlHZm4zIY4Be-ToCxb86TWCg',
    appId: '1:461060498166:android:dd836e38dd2d4e1279c2d7',
    messagingSenderId: '461060498166',
    projectId: 'rideshare-007bond',
    storageBucket: 'rideshare-007bond.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFJc9SlAi7G55-NcMHhVgVxQFt8_xp20',
    appId: '1:461060498166:ios:a78b0442216a2cca79c2d7',
    messagingSenderId: '461060498166',
    projectId: 'rideshare-007bond',
    storageBucket: 'rideshare-007bond.firebasestorage.app',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdFJc9SlAi7G55-NcMHhVgVxQFt8_xp20',
    appId: '1:461060498166:ios:a78b0442216a2cca79c2d7',
    messagingSenderId: '461060498166',
    projectId: 'rideshare-007bond',
    storageBucket: 'rideshare-007bond.firebasestorage.app',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDembYfDpkLOWOP9jbNY5KncXKOQDlGIT0',
    appId: '1:461060498166:web:a30af6d9c110a9f979c2d7',
    messagingSenderId: '461060498166',
    projectId: 'rideshare-007bond',
    authDomain: 'rideshare-007bond.firebaseapp.com',
    storageBucket: 'rideshare-007bond.firebasestorage.app',
  );
}
